spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hhnail
    username: root
    password: 123456

server:
  port: 8080 # web服务端口号
  servlet:
    multipart:
      enabled: true # 启用文件上传
      location: # 上传文件临时保存位置
      max-file-size: 50MB # 单个文件上传最大大小限制
      max-request-size: 100MB # 单次请求主体最大大小限制
  mvc:
    format:
      date: yyyy-MM-dd # 日期格式
      date-time: yyyy-MM-dd HH:mm:ss # 日期时间格式
      time: HH:mm:ss # 时间格式

#logging:
#  config: logback.xml
#  level:
#    com.itcodai.course03.dao: trace
#mybatis:
#  mapper-locations: classpath*:mapper/*Mapper.xml
mybatis-plus:
    # 自定义xml文件路径
    mapper-locations: classpath:/mapper/*Mapper.xml